#!/usr/bin/env python3
"""
Build data/app-data.json from the raw source files in data/.

Rerun this each year after refreshing the three fiscal-year source files:
  data/county-budget-fy2025-26.json
  data/tax-districts-fy2025-26.json
  data/code-areas-fy2025-26.json
(rename them for the new fiscal year and update the paths below).

Also folds in the plain-language content layer (does not change annually
the way the fiscal-year files do, but only needs to stay in sync with the
`category` values used in tax-districts-fy2025-26.json and the vocabulary
actually used in the app's copy):
  data/category-groups.json
  data/glossary.json
  data/headline-stats.json

And the school district drill-down (school-funding-fy2024-25.json is
itself generated by scripts/build_school_funding.py from a separately
downloaded ODE CSV -- run that first if it's missing or stale):
  data/school-districts.json
  data/school-funding-fy2024-25.json

This script does NOT fetch anything from the network. It only reconciles
and reshapes data that has already been transcribed from the official PDFs.

Key job: for every code area, compute the composite tax rate by summing
`bill_rate` across the districts listed for that code area, rather than
trusting the source PDF's own printed subtotal (which was OCR'd from a
dense multi-column table and did not always reconcile cleanly). Any code
area where the computed sum and the printed total disagree by more than a
rounding error is flagged so the app can surface it instead of silently
picking a number.
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, "data")

# Some code-area district lists use abbreviated names that differ from the
# master list's full names. Map those here.
NAME_ALIASES = {
    "ESD": "ESD (Education Service District)",
    "SWOCC": "SWOCC (Southwestern Oregon Community College)",
}

ROUNDING_TOLERANCE = 0.02  # $ per $1,000 assessed value

# Which K-12 district applies to a code area is derived directly from which
# "School ..." tax line item is actually present in that code area's
# district list, NOT from school-districts.json's `matches_property_tax_code_areas`
# area-name text. The two disagree for one case (Pistol River code 16-3 is
# tagged there as partly Brookings-Harbor, but its actual tax-roll district
# is "School CC 1"), and deriving it from the same certified data already
# driving the rest of the app is both more precise (per-code-area rather
# than per-named-area -- useful since a single named area can span more
# than one school district, as 16-3 shows) and guaranteed self-consistent
# with the property-tax breakdown the person is already looking at.
SCHOOL_CODE_TO_KEY = {
    "School CC 1": "central_curry",
    "School 2CJ": "port_orford_langlois",
    "School 17-C": "brookings_harbor",
}

# school-districts.json's `current_news_note` fields are written for the
# person maintaining this data, not the app's readers -- e.g. the
# Brookings-Harbor one ends with "do not include it in current-year totals,
# but it may be worth a 'heads up' note in the app", which is an instruction
# to whoever builds this, not a fact about the district. Rather than pass
# that prose straight into the UI, override it here with reader-facing
# copy. Falls back to the raw field for any future note that doesn't need
# an override -- but check new ones for the same mixed-audience problem
# before trusting the fallback.
NEWS_NOTE_OVERRIDES = {
    # Originally a "heads up, this may pass" note about a pending May 2026
    # bond vote. The vote has since happened (see upcoming-changes.json) --
    # updated here to report the actual outcome rather than leaving stale
    # future-tense language about a measure that already failed.
    "School 17-C": (
        "A school bond measure (Measure 8-118) for facility repairs and "
        "upgrades was on the May 2026 ballot and failed (about 58% against). "
        "The district does not receive the $6.1 million in state matching "
        "funds (OSCIM) that were contingent on it passing, and the current "
        "School 17-C tax rate shown above is unaffected. See the Recent & "
        "Upcoming Changes tab for details."
    ),
}

# Explicit slugs for glossary terms (glossary.json's `terms` plus
# enrollment-funding-explainer.json's `glossary_additions`), so the app can
# look up a definition by a stable key instead of matching on the display
# string. Add an entry here (using the term string verbatim from its source
# file) whenever a new term is added to either file.
GLOSSARY_SLUGS = {
    "Assessed Value": "assessed_value",
    "Real Market Value": "real_market_value",
    "Tax Rate / Bill Rate": "tax_rate",
    "Levy": "levy",
    "Permanent Rate": "permanent_rate",
    "Local Option Levy": "local_option_levy",
    "Bond": "bond",
    "Urban Renewal": "urban_renewal",
    "Code Area": "code_area",
    "Taxing District": "taxing_district",
    "Compression / Measure 5 (M5) Limit": "compression_m5",
    "ADMw (Weighted Average Daily Membership)": "admw",
    "State School Fund": "state_school_fund",
    "General Purpose Grant": "general_purpose_grant",
    "Public Charter School": "public_charter_school",
}


def load(name):
    with open(os.path.join(DATA, name)) as f:
        return json.load(f)


def main():
    budget = load("county-budget-fy2025-26.json")
    districts_doc = load("tax-districts-fy2025-26.json")
    code_areas_doc = load("code-areas-fy2025-26.json")
    category_groups_doc = load("category-groups.json")
    glossary_doc = load("glossary.json")
    headline_stats_doc = load("headline-stats.json")
    school_districts_doc = load("school-districts.json")
    school_funding_doc = load("school-funding-fy2024-25.json")
    enrollment_funding_doc = load("enrollment-funding-explainer.json")
    non_property_tax_revenue_doc = load("non-property-tax-revenue.json")
    health_explainer_doc = load("health-district-explainer.json")
    upcoming_changes_doc = load("upcoming-changes.json")
    fire_context_doc = load("fire-district-context.json")

    districts = districts_doc["districts"]
    rate_by_name = {d["name"]: d["bill_rate"] for d in districts}
    district_by_name = {d["name"]: d for d in districts}

    # Map each raw `category` (school, fire, county, ...) to its plain-
    # language display group id (schools, fire, county, cities, health,
    # library, roads, other_local). Fail loudly if a category has no home,
    # or a group claims a category no district actually uses -- both mean
    # category-groups.json is out of sync with tax-districts-fy2025-26.json.
    category_to_group = {}
    for g in category_groups_doc["display_groups"]:
        for cat in g["source_categories"]:
            category_to_group[cat] = g["id"]

    used_categories = {d["category"] for d in districts}
    unmapped = used_categories - set(category_to_group)
    if unmapped:
        raise SystemExit(
            f"category-groups.json does not map these district categories: "
            f"{unmapped} -- add them to a display group."
        )
    unused = set(category_to_group) - used_categories
    if unused:
        raise SystemExit(
            f"category-groups.json maps categories no district uses: "
            f"{unused} -- likely stale, double check."
        )

    for d in districts:
        d["group"] = category_to_group[d["category"]]

    # Glossary: key by an explicit slug (GLOSSARY_SLUGS) rather than the
    # display string, so the app can look up a definition by a stable key.
    # Merges glossary.json's terms with enrollment-funding-explainer.json's
    # glossary_additions into the same lookup -- one glossary UI, not two.
    glossary_by_slug = {}
    for term in glossary_doc["terms"] + enrollment_funding_doc["glossary_additions"]:
        slug = GLOSSARY_SLUGS.get(term["term"])
        if slug is None:
            raise SystemExit(
                f"glossary.json has a term with no slug mapping: "
                f"{term['term']!r} -- add it to GLOSSARY_SLUGS."
            )
        glossary_by_slug[slug] = {
            "term": term["term"],
            "short_definition": term["short_definition"],
            "longer_note": term.get("longer_note"),
        }

    def resolve(name):
        return NAME_ALIASES.get(name, name)

    flagged = []
    areas_out = []

    for area in code_areas_doc["geographic_areas"]:
        codes_out = []
        for ca in area["code_areas"]:
            resolved_names = [resolve(n) for n in ca["districts"]]
            unknown = [n for n in resolved_names if n not in rate_by_name]
            if unknown:
                raise SystemExit(
                    f"Unknown district name(s) {unknown} in code area "
                    f"{area['area_name']} / {ca['code']} -- fix NAME_ALIASES "
                    f"or the source data."
                )

            computed = round(sum(rate_by_name[n] for n in resolved_names), 4)
            printed = ca.get("total_code_rate_as_printed")
            diff = round(computed - printed, 4) if printed is not None else None
            is_flagged = diff is None or abs(diff) > ROUNDING_TOLERANCE

            school_matches = [SCHOOL_CODE_TO_KEY[n] for n in resolved_names if n in SCHOOL_CODE_TO_KEY]
            if len(school_matches) != 1:
                raise SystemExit(
                    f"Code area {area['area_name']} / {ca['code']} matches "
                    f"{len(school_matches)} K-12 school districts (expected exactly "
                    f"1): {school_matches} -- check its district list."
                )

            entry = {
                "code": ca["code"],
                "representative": bool(ca.get("representative", False)),
                "school_district_key": school_matches[0],
                "districts": [
                    {
                        "name": n,
                        "category": district_by_name[n]["category"],
                        "group": district_by_name[n]["group"],
                        "bill_rate": district_by_name[n]["bill_rate"],
                        "note": district_by_name[n].get("note"),
                    }
                    for n in resolved_names
                ],
                "computed_rate": computed,
                "printed_rate_as_source": printed,
                "rate_diff": diff,
                "flagged": is_flagged,
                "source_note": ca.get("note"),
            }
            codes_out.append(entry)

            if is_flagged:
                flagged.append(
                    {
                        "area": area["area_name"],
                        "code": ca["code"],
                        "computed_rate": computed,
                        "printed_rate_as_source": printed,
                        "diff": diff,
                    }
                )

        areas_out.append(
            {
                "area_name": area["area_name"],
                "nearest_city": area.get("nearest_city"),
                "code_areas": codes_out,
            }
        )

    # health-district-explainer.json's own scope note is written as an
    # instruction to whoever builds this ("worth double-checking that
    # mapping"), not reader copy -- verify it here against the actual code
    # area data and write a clean, reader-facing note from what's actually
    # true, rather than passing the instruction through verbatim.
    health_code_count = sum(len(a["code_areas"]) for a in areas_out)
    health_covered = sum(
        1 for a in areas_out for ca in a["code_areas"] if any(d["name"].startswith("Health District") for d in ca["districts"])
    )
    fully_uncovered_areas = [
        a["area_name"]
        for a in areas_out
        if not any(any(d["name"].startswith("Health District") for d in ca["districts"]) for ca in a["code_areas"])
    ]
    health_scope_note = (
        f"The Health District's boundaries do not cover the entire county -- only "
        f"{health_covered} of the county's {health_code_count} code areas include a "
        f"Health District rate"
        + (f", and the {fully_uncovered_areas[0]} has none of it at all" if len(fully_uncovered_areas) == 1 else "")
        + ". Unlike the county's own permanent rate, not every Curry County property pays this one."
    )

    # County budget: build display-friendly groupings.
    # Non-Departmental is a pass-through hub (transfers), so it is excluded
    # from the "where your county tax dollar goes" department chart to avoid
    # double counting, but its total is still shown separately for context.
    gf = budget["general_fund_departments"]
    gf_chart = [d for d in gf if not d["department"].startswith("Non-Departmental")]
    non_dept = next(
        (d for d in gf if d["department"].startswith("Non-Departmental")), None
    )

    # The Road Capital Improvement Fund is mostly a multi-year reserve, not a
    # single year's operating spend (per its note in the source budget), so it
    # would swamp every other department if mixed into a one-year spending
    # chart. Exclude it the same way as Non-Departmental, and surface it
    # separately for context instead.
    road_all = budget["road_fund"]
    road_chart = [d for d in road_all if d["fund"] != "Road - Capital Improvement Fund"]
    road_reserve = next(
        (d for d in road_all if d["fund"] == "Road - Capital Improvement Fund"), None
    )
    gvs = budget["general_vehicle_services_fund"]
    other = budget["other_funds"]
    sheriff = budget["sheriff_special_revenue_sub_funds"]

    county_departments_chart = (
        [{"department": d["department"], "group": "General Fund", "total_requirements": d["total_requirements"]} for d in gf_chart]
        + [{"department": d["fund"], "group": "Sheriff's Office", "total_requirements": d["total_requirements"]} for d in sheriff]
        + [{"department": d["fund"], "group": "Road Fund", "total_requirements": d["total_requirements"]} for d in road_chart]
        + [{"department": d["fund"], "group": "Vehicle Services", "total_requirements": d["total_requirements"]} for d in gvs]
        + [{"department": d["fund"], "group": "Other Funds", "total_requirements": d["total_requirements"]} for d in other]
    )
    county_chart_total = sum(d["total_requirements"] for d in county_departments_chart)

    # ---------- School district drill-down ----------
    # Join key is a tax-data code (e.g. "School CC 1"), not the district
    # name -- school-districts.json, tax-districts-fy2025-26.json, and
    # school-funding-fy2024-25.json each spell district names slightly
    # differently ("Central Curry School District 1" vs "Central Curry SD 1"),
    # but all three agree on the tax-data code strings.
    funding_by_code = {}
    for fd in school_funding_doc["districts"]:
        for code in fd["code_in_tax_data"]:
            funding_by_code[code] = fd

    def school_tax_rate_info(codes):
        # Sum of the actual FY2025-26 certified rate(s) for a district's
        # school tax line item(s) (e.g. a K-12 district plus its separate
        # bond line, where one exists).
        return round(sum(rate_by_name.get(c, 0.0) for c in codes), 4)

    k12_out = []
    for d in school_districts_doc["k12_districts"]:
        codes = [d["code_in_tax_data"]] + ([d["code_in_tax_data_bond"]] if d.get("code_in_tax_data_bond") else [])
        funding = funding_by_code.get(d["code_in_tax_data"])
        k12_out.append(
            {
                "key": SCHOOL_CODE_TO_KEY[d["code_in_tax_data"]],
                "official_name": d["official_name"],
                "code_in_tax_data": codes,
                "current_tax_rate": school_tax_rate_info(codes),
                "hq_city": d.get("hq_city"),
                "website": d.get("website"),
                "communities_served": d.get("communities_served", []),
                "schools": d.get("schools", []),
                "history_note": d.get("history_note"),
                "enrollment_note": d.get("enrollment_note"),
                "current_news_note": NEWS_NOTE_OVERRIDES.get(d["code_in_tax_data"], d.get("current_news_note")),
                "funding": funding,
            }
        )

    regional_out = []
    for d in school_districts_doc["regional_education_entities"]:
        funding = funding_by_code.get(resolve(d["code_in_tax_data"]))
        regional_out.append(
            {
                "code_in_tax_data": d["code_in_tax_data"],
                "official_name": d["official_name"],
                "note": d.get("note"),
                "needs_verification": d.get("needs_verification", False),
                "funding": funding,
            }
        )

    schools_out = {
        "k12_districts": k12_out,
        "regional_education_entities": regional_out,
        "already_sourced_facts": school_districts_doc["already_sourced_facts"],
        "funding_meta": school_funding_doc["_meta"],
        # Only the two reader-facing content blocks are passed through.
        # enrollment_funding_doc's `worked_example_guidance` is addressed to
        # whoever builds this feature (it says so explicitly: "guidance for
        # building..."), not reader copy -- the app builds its own live
        # interactive sentence instead of rendering that field verbatim.
        "enrollment_funding_explainer": {
            "allocation": enrollment_funding_doc["how_state_funding_is_allocated"],
            "charter_transfer": enrollment_funding_doc["charter_school_funding_transfer"],
        },
    }

    app_data = {
        "meta": {
            "fiscal_year": "2025-2026",
            "generated_note": (
                "Generated by scripts/build_data.py from the raw source files "
                "in data/. Do not hand-edit; re-run the script after updating "
                "the raw sources for a new fiscal year."
            ),
            "sources": [
                {
                    "label": "Curry County 2025-2026 Proposed Budget",
                    "url": budget["_meta"]["source_url"],
                    "status": budget["_meta"]["status"],
                },
                {
                    "label": "Curry County 2025-26 Tax Roll Summary by Taxing Districts (certified)",
                    "url": None,
                    "status": "Certified by Kiley Wegner, Curry County Assessor",
                },
                {
                    "label": "Curry County Tax Rates by Code Area, 2025-2026",
                    "url": None,
                    "status": "Assessor's Office; composite rates recomputed from district-level rates, see data notes",
                },
            ],
        },
        "county_permanent_tax_rate": budget["county_permanent_tax_rate"],
        "county_wide_pie_breakdown_as_published": districts_doc["county_wide_pie_breakdown_as_published"],
        "districts": districts,
        "geographic_areas": areas_out,
        "flagged_code_areas": flagged,
        "county_budget": {
            "total_combined_budget": budget["total_combined_budget"],
            "departments_chart": county_departments_chart,
            "departments_chart_total": county_chart_total,
            "non_departmental": non_dept,
            "road_capital_reserve": road_reserve,
            "officials": budget["county_officials_fy2025_26"],
            "non_property_tax_revenue": {
                "headline": non_property_tax_revenue_doc["headline"],
                "sources": non_property_tax_revenue_doc["revenue_sources"],
                "pull_quote": non_property_tax_revenue_doc["app_display_guidance"]["good_pull_quote"],
            },
        },
        "category_groups": category_groups_doc["display_groups"],
        "glossary": glossary_by_slug,
        "health_district_explainer": {
            "official_name": health_explainer_doc["official_name"],
            "what_it_is": health_explainer_doc["what_it_is"],
            "important_scope_note": health_scope_note,
            "what_it_operates": health_explainer_doc["what_it_operates"],
            "why_this_matters_for_a_rural_coastal_county": health_explainer_doc[
                "why_this_matters_for_a_rural_coastal_county"
            ],
        },
        "fire_district_context": {
            "headline": fire_context_doc["general_context"]["headline"],
            # fire-district-context.json's own text ends with "...see
            # 'known_gaps' below" -- a reference to that JSON file's own
            # sibling key, meaningless to a reader of the app. The app
            # already renders its own honest-gap sentence separately
            # (assets/app.js's fireDrilldownMarkup), so trim the dangling
            # citation rather than pass it through verbatim.
            "why_rates_vary_generally": fire_context_doc["general_context"]["why_rates_vary_generally"].split(
                " None of these specifics"
            )[0],
        },
        "upcoming_changes": {
            "recent_measures": upcoming_changes_doc["recent_measures"],
            "statewide_context": upcoming_changes_doc["statewide_context_worth_including"],
        },
        "headline_stats": {
            "headline_facts": headline_stats_doc["headline_facts"],
            "dollar_story_formula": headline_stats_doc["dollar_story_formula"],
            "opening_section_copy": headline_stats_doc["opening_section_copy_draft"],
            "caveat_copy": headline_stats_doc["caveat_copy_draft"],
        },
        "schools": schools_out,
    }

    out_path = os.path.join(DATA, "app-data.json")
    with open(out_path, "w") as f:
        json.dump(app_data, f, indent=2)

    print(f"Wrote {out_path}")
    print(f"{len(flagged)} of {sum(len(a['code_areas']) for a in areas_out)} code areas flagged for rate discrepancy > {ROUNDING_TOLERANCE}")
    for f_ in flagged:
        print(f"  {f_['area']} / {f_['code']}: computed={f_['computed_rate']} printed={f_['printed_rate_as_source']} diff={f_['diff']}")


if __name__ == "__main__":
    main()
